---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: es
  label: Pages en espagnol
  create: none
  match: "**/*.md"
- type: directory
  path: es/_posts
  label: Posts en espagnol
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: fr
  label: Pages en français
  create: none
  match: "**/*.md"
- type: directory
  path: fr/_posts
  label: Posts en français
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: imgs
public_path: "/mepierdoparaver/imgs"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
